import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { ThemeProvider } from "~/components/theme-provider";

import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  RedirectToSignIn,
} from "@clerk/nextjs";

import { TRPCReactProvider } from "~/trpc/react";
import ConvexClientProvider from "./ConvexClientProvider";
import { SidebarProvider } from "~/components/ui/sidebar";
import { AppSidebar } from "./appSideBar";
import { Toaster } from "~/components/ui/sonner";
import { ReactScan } from "./reactScan";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <TRPCReactProvider>
        <ConvexClientProvider>
          <html
            lang="en"
            className={`${geist.variable}`}
            suppressHydrationWarning
          >
            <ReactScan />
            <body>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <SignedIn>
                  <SidebarProvider>
                    <AppSidebar />
                    <main className="flex min-h-full w-full">{children}</main>
                  </SidebarProvider>
                </SignedIn>
                <SignedOut>
                  <RedirectToSignIn />
                </SignedOut>
                <Toaster />
              </ThemeProvider>
            </body>
          </html>
        </ConvexClientProvider>
      </TRPCReactProvider>
    </ClerkProvider>
  );
}
